# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e28eb38d87a1870aa0366428bafe16dcbbe2845390de887df873b503f3b9e92e043c6348eb8eec2ad139f1d15e8debc7bdfa46ca73c4ec0b4fa04f283682562f

test:
  secret_key_base: fb3cc262daaae2a5e1bf7410b417a733732735ddbe5e92d8718a6bf45db06d26d7d16bb97ff72ad99c3814d7faa1262d04954b1093135da047fdd503e2964bbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
